### ISSUE TITLE
conda install ONT environment fails

### ISSUE THREAD

**Issue by estolle** [VGP/vgp-assembly#43]
Hi there

I wanted to try the pipeline on some insect data (Illumina + ONT reads).

I seem to have problems to use your conda yml file for ONT. I am getting this error:

Solving environment: failed
ResolvePackageNotFound:
  - gcc_impl_linux-64==7.3.0=habb00fd_2

I could not yet solve it. The pacbio install works.

If I change the listed problematic package to gcc_impl_linux-64=7.3.0 or gcc_impl_linux-64 then it comes up with loads! of conflicts.

Any ideas?

I also wonder whether I could use the pacbio pipeline using error-corrected ONT reads (fasta, corrected with ratatosk from ca 80X coverage)?

Thanks,
Eckart

**Comment by estolle** [comment]
my conda info is this:

active environment : None
            shell level : 0
       user config file : /home/estolle/.condarc
 populated config files : /home/estolle/.condarc
          conda version : 4.8.2
    conda-build version : 3.18.11
         python version : 3.7.6.final.0
       virtual packages : __glibc=2.17
       base environment : /share/scientific_bin/anaconda3/2020.02  (read only)
           channel URLs : https://conda.anaconda.org/bioconda/linux-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://conda.anaconda.org/w-l/linux-64
                          https://conda.anaconda.org/w-l/noarch
                          https://conda.anaconda.org/r/linux-64
                          https://conda.anaconda.org/r/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /share/scientific_bin/anaconda3/2020.02/pkgs
                          /home/estolle/.conda/pkgs
       envs directories : /home/estolle/.conda/envs
                          /share/scientific_bin/anaconda3/2020.02/envs
               platform : linux-64
             user-agent : conda/4.8.2 requests/2.22.0 CPython/3.7.6 Linux/3.10.0-693.5.2.el7.x86_64 centos/7.4.1708 glibc/2.17
                UID:GID : 1018:1018
             netrc file : None
           offline mode : False

**Comment by gf777** [comment]
Hi Eckart, sorry I must have overlooked this message as it wasn't mentioning the mitoVGP pipeline directly. You are referring to this right? Short answer to your second question: no you cannot use the Pacbio pipeline for ONT data, the two data types have to be treated differently and hence they undergo different steps, particularly during polishing. Were you able to solve the issue in the meantime? If not I can look into it. Best, Giulio

**Comment by estolle** [comment]
Dear Giulio

Thanks alot. I've tried a similar approach with my ONT assemblies/reads which in principle should work. But It seems the MT is not part of the two assembled genomes I analyzed nor has useful amounts of MT reads. I think I'll leave it at that for the moment.

**Comment by gf777** [comment]
Sounds good Eckart. Don't hesitate to contact me if you have any more requests. Best Giulio

**Comment by arangrhie** [comment]
Feel free to reopen if needed.
