### ISSUE TITLE
Chromosome status estimation

### ISSUE THREAD

**Issue by zhoudreames** [VGP/vgp-assembly#47]
hello ,in your article, you use the  Hi-c data interaction signs to estimate the proportion of Chromosome status,but i dont know how to calculate this value.thank you for your help

**Comment by zhoudreames** [comment]
@mcshane @skoren @Arkarachai @godotgildor

**Comment by Arkarachai** [comment]
How about you sign up for DNAnexus account first and I will send training video that Arang taught the trainee? The free account should come with enough credit that you can download all videos once and watch them. We make the knowledge open, but please provide citations to our main assembly publication when you use this knowledge. 
Also, I personally recommend you check the VGP consoirtum website. We have open door policy.

**Comment by zhoudreames** [comment]
my DNAnexus account name is "Dreames Ciro",thank you for your help~

**Comment by zhoudreames** [comment]
my DNAnexus account  username  is " zm909397186"

**Comment by Arkarachai** [comment]
Sounds good. I can detect your user in system now. Could you create one empty project and share with user-chai? I will copy video there and you can download it.

**Comment by zhoudreames** [comment]
> Sounds good. I can detect your user in system now. Could you create one empty project and share with user-chai? I will copy video there and you can download it.

ok ,I have shared your the subject

**Comment by Arkarachai** [comment]
sorry, Zhou. I forgot to mention that it has to be AWS US East region. Anyhow, I create a new project transfer ownership to you. Once you accept, you can download the files. Once you download them, you can remove the project, so you won't get the bill. 
If you want to use these workflows on DNAnexus, please contact support@DNAnexus.com. However, you can use free version of it on your own infrastructure using code in /pipeline folder as I mentioned.

**Comment by zhoudreames** [comment]
> sorry, Zhou. I forgot to mention that it has to be AWS US East region. Anyhow, I create a new project transfer ownership to you. Once you accept, you can download the files. Once you download them, you can remove the project, so you won't get the bill.
> If you want to use these workflows on DNAnexus, please contact [support@DNAnexus.com](mailto:support@DNAnexus.com). However, you can use free version of it on your own infrastructure using code in /pipeline folder as I mentioned.

thank you so mush ,I feel very excited！I have received the file and vidio，it must help me so much.
