### ISSUE TITLE
error in Asset

### ISSUE THREAD

**Issue by zhoudreames** [VGP/vgp-assembly#48]
when I run asset/bin/ast_bion_bnx, I got the error show blow:
Segmentation fault (core dumped)

I show you my run script:
/home/Duhuipeng/zm/Biosoft/asset/bin/ast_bion_bnx exp_refineFinal1_r.cmap exp_refineFinal1_q.cmap exp_refineFinal1.xmap BMX_v122_BSPQI_0kb_0labels_key.txt   > bionano_"saphyr"_"BspQI".bed   2>ast_bion_bnx_"saphyr"_"BspQI".log

I dont know where is problem,thank you for your help!

**Comment by zhoudreames** [comment]
@godotgildor @skoren @mcshane @Arkarachai  thank you for you help!!

**Comment by arangrhie** [comment]
Hi @zhoudreames ,

Check your ast_bion_bnx_saphyr_BspQI.log file and file to the original [asset repo](https://github.com/dfguan/asset).

**Comment by zhoudreames** [comment]
solved
