### ISSUE TITLE
10X align

### ISSUE THREAD

**Issue by zhoudreames** [VGP/vgp-assembly#49]
in your pipeline,the longrange software using fixed  fastq format in blow：
_S*_L00*_R1_001.fastq.gz
_S*_L00*_R2_001.fastq.gz
 if the 10x fastq data  trim barcode or not ？

 I got the average molecule coverage is  234 when I aligned 10X data by using longrange,but  the mean depth only is 89 .I dont know what means the average molecule coverage, and  is the value reasonable？

**Comment by Arkarachai** [comment]
I can answer the first part. For longranger step, the 10x is not trimmed.

**Comment by arangrhie** [comment]
Hi @zhoudreames, yes, the 10x fastq data contain the barcode info.
The molecule coverage in asset are inferred from these barcodes, which is different from the physical coverage of the reads.
Reads containing same barcodes within certain length are considered as one molecule, which could contain physical coverage gaps.

**Comment by zhoudreames** [comment]
> Hi @zhoudreames, yes, the 10x fastq data contain the barcode info.
> The molecule coverage in asset are inferred from these barcodes, which is different from the physical coverage of the reads.
> Reads containing same barcodes within certain length are considered as one molecule, which could contain physical coverage gaps.



> I can answer the first part. For longranger step, the 10x is not trimmed.

thank you so mush
