### ISSUE TITLE
asset bionano problem

### ISSUE THREAD

**Issue by zhoudreames** [VGP/vgp-assembly#51]
in my project,and human CHM13 v1.0 assembly,I used asset to evaluate the structure of assembly,but it both present a problem about binano low support region ,the no good result show in blow:
in CHM13 v1.0 Assembly:
![image](https://user-images.githubusercontent.com/54714639/105499553-9c604180-5cfc-11eb-92f6-abdbcf7ad40c.png)
in the red square,the binano low support region covered the whole chromosome.I used your recommend parameter that  requires regions to have  at least 10 molecule coverage or 0.5 x (average molecule coverage). i dont know why ,and i try to change the parameter into 0.3,0.2,0.1, it didnt work. can you help me?
and this phenomenon also present my project ,i think this is common problem . this problem show in blow:
![image](https://user-images.githubusercontent.com/54714639/105500609-1513cd80-5cfe-11eb-968a-8e05a55462a9.png)

**Comment by arangrhie** [comment]
Hi @zhoudreames , we noticed the bionano coverage dropouts too. It seems like it is due to the lack of sequence motif bionano is using for labeling. Note the centromeric sequence has a very limited sequence pattern compared to the rest of the genome.
