### ISSUE TITLE
mitoVGP crashes on start

### ISSUE THREAD

**Issue by cement-head** [VGP/vgp-assembly#52]
Crashes on start:

```
$ ./mitoVGP -a pacbio -s Rana_sylvatica -i aRanSyl -r NC_027236.1.fasta -t 124 


++++                        mitoVGP v2.0                         ++++
++++ The Vertebrate Genomes Project Mitogenome Assembly Pipeline ++++
++++     Credit: Giulio Formenti gformenti@rockefeller.edu       ++++


Started at at: 2021-02-16 08-27-23

With command:

./mitoVGP

Using 'NC_027236.1.fasta' as reference

Genome size not provided, using reference genome size: 17592 bp

Command: sh -e scripts/mtDNApipe -s Rana_sylvatica -i aRanSyl -r NC_027236.1.fasta -g 17592 -t 124 -a pacbio 2>&1 | tee Rana_sylvatica/aRanSyl/assembly_MT_rockefeller/intermediates/log/aRanSyl_mtDNApipe_20210216-082724.out
scripts/mtDNApipe: 3: set: Illegal option -o pipefail
scripts/blastMT: 3: set: Illegal option -o pipefail
```

**Comment by gf777** [comment]
Hi @cement-head ,

this looks like an issue with the linux version (what OS are you using?). Your system most likely does not support the (safer) -o pipefail option (https://vaneyckt.io/posts/safer_bash_scripts_with_set_euxo_pipefail/). You are probably good removing it from all the scripts where it is present.

**Comment by cement-head** [comment]
Ubuntu 18.04.5 LTS; okay will try that

**Comment by cement-head** [comment]
Okay, dash in Ubuntu (not bash) doesn't recognise pipefail: https://askubuntu.com/questions/886537/set-e-o-pipefail-not-working-on-bash-script-on-ubuntu-16

**Comment by gf777** [comment]
Thanks for checking this. It then seems more like a symlink issue in your environment, since the shebang line requests bash (`#!/bin/bash`). If you confirm we can close I think. Thanks!

**Comment by cement-head** [comment]
Yes; switching to bash prompt doesn't help. I'm using a very vanilla 18.04.5 LTS install; just for bioinformatics.  Looks as though starting from bash bounces it back to dash. Current workaround is to comment out

`#set -e -o pipefail `

**Comment by gf777** [comment]
Thanks, good for other users who may encounter the same issue to know..closing!

**Comment by cement-head** [comment]
What DISTRO was this script coded on? CentOS? Other RedHat derivative?

**Comment by gf777** [comment]
Currently working fine on Red Hat Enterprise Linux Server 7.5. Tested a while ago on CentOS also worked fine. Maybe open a new thread with the specific issues?
