### ISSUE TITLE
QUESTION: Does mitoVGP need pacbio RAW data (BAM) files as input?

### ISSUE THREAD

**Issue by cement-head** [VGP/vgp-assembly#53]
Or can it accept FASTQ files?

**Comment by gf777** [comment]
Yes, because the bam is required by Arrow for polishing.

**Comment by cement-head** [comment]
(1) Please stop closing issues that are still in discussion.
(2) So, does mitoVGP need the entire PacBioSII output folder, or just the <subreads.bam> file(s)?

**Comment by gf777** [comment]
Hi @cement-head ,

sorry since the question was answered I wanted to avoid forgetting closing the topic. You need the subreads.bam, given as a txt list of files to the option -1
