### ISSUE TITLE
plant mitochondrial genomes?

### ISSUE THREAD

**Issue by romseg** [VGP/vgp-assembly#56]
Hi,

I am wondering how well would mitoVGP work at assembling plant mitochondrial genomes? Plant mitogenomes are very long, non-conserved and often with multiple chromosomal structures. Thanks.

**Comment by richarddurbin** [comment]
Marcela has been actively looking at this with respect to her mitoHiFi from CCS reads, and at chloroplast (plastid) genomes.

Richard

**Comment by gf777** [comment]
Hi @romseg 

mitoVGP was never developed/tested to assemble mitochondria. Some of the steps may apply, but others are tailored to mitochondria and would require optimization. You could simply try and see what you get, then fork mitoVGP to adapt it. For CLR there is also Organelle_PBA(https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5219736/). If you have HiFi data you should definitely try mitoHiFi as @richarddurbin suggests.

Best

Giulio

**Comment by romseg** [comment]
Thanks for the information. I am looking into mitoHiFi and Organelle_PBA.

I also have Nanopore and 10X data, do you know any program that would use either Nanopore or 10X data to assemble plant mitochondrial genomes?

I mean the linked information of 10X, and not just for polishing. Although I would guess that the span of the linked information could be larger than the mitochondrial molecule itself, but not sure. Thanks again.

Romulo

**Comment by marcelauliano** [comment]
Dear Romulo. At the moment, MitoHifi-plants is not available on GitHub, but I can send you the code. Please write me at mu2@sanger.ac.uk
Do you have CLR or HiFi reads?

**Comment by gf777** [comment]
Hi @romseg 

mitoVGP can also use nanopore data. I am not aware of any software using 10x information, I doubt there is one. You could use the barcodes to exclude reads that don't share barcodes given a certain threshold, but it's probably an overkill to assemble mito.

All the best 

Giulio

**Comment by romseg** [comment]
Dear Marcela @marcelauliano. Thanks for your offer, I will be contacting you by email.

Dear Giulio @gf777. Thanks for your assistance. I haven't seen any software using 10x either.
