### ISSUE TITLE
mitoVGP crashes on start

### ISSUE THREAD

**Issue by mcurto** [VGP/vgp-assembly#61]
Hi,
when running mitoVGP for nanopore I am getting this error: 
scripts/mtDNApipe: 3: set: Illegal option -o pipefail
scripts/blastMT: 3: set: Illegal option -o pipefail

Even when running the program with the test data:
./mitoVGP -a ONT -s Mastacembelus_armatus -i fMasArm1 -r mtDNA_Mastacembelus_armatus.fasta -t 24 -b variantCaller

Do you know what might be wrong?
Thanks,
Manuel

**Comment by skoren** [comment]
I'll guess you're on Ubuntu. There's an issue with Ubuntu where the default shell is dash and even scripts that have bash specified in the shebang run in dash which doesn't support pipe fail (see https://askubuntu.com/questions/886537/set-e-o-pipefail-not-working-on-bash-script-on-ubuntu-16 for example). Try running it as `bash mitoVGP` explicitly.

**Comment by mcurto** [comment]
Thanks Sergey. This means I will have to run each script individually,
right? When I try to run bash mitoVGP I get the same error message.


Sergey Koren ***@***.***> escreveu no dia segunda, 17/01/2022
à(s) 02:42:

**Comment by skoren** [comment]
It looks like mitoVGP itself launches jobs as `sh scripts/mtDNApipe`, etc. That is not correct since it uses bashisms so it should be `bash scripts/mtDNApipe`, etc. You should be able to update mitoVGP to use bash and I expect it will run. @gf777 you should update the repo to bash as well.

**Comment by gf777** [comment]
right, better specify. I just did. Let me know if this fixes the issue
