### ISSUE TITLE
Pipeline for Polishing Canu assembly with Illumina Reads

### ISSUE THREAD

**Issue by iek** [VGP/vgp-assembly#80]
Hello, I'm sorry for the inconvenience, but is there a tutorial somewhere on how to polish a Canu assembly of Nanopore reads using Illumina reads? The Canu github linked me to here: https://github.com/VGP/vgp-assembly/tree/master/pipeline/freebayes-polish . However, I don't see a tutorial on how to exactly begin polishing. 

Do I perhaps just use the following command: `./_submit_longranger_freebayes.sh assembly.fasta reference_genome.fasta` along with putting the illumina reads in `/data/rhiea/<genome>/genomic_data/`?

**Comment by arangrhie** [comment]
Hello, apologies for the very delayed response! There are multiple ways to polish - the freebayes pipeline being one of it, which however, the pipeline linked would assume using linked-reads (longranger part).

Try align your Illumina reads with the [bwa mem pipeline](/VGP/vgp-assembly/tree/master/pipeline/bwa) instead, then call variants (SNV errors) with either freebayes, GATK or DeepVariant.

My current best-practice for a regular Canu ONT assembly (not phased) would be using DeepVariant + Merfin(https://github.com/arangrhie/merfin).

Best,
Arang
